version: '3.1'

services:
  www:
    build: .
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html/
    networks:
      - default
    links:
      - db
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: syntrafs
      MYSQL_USER: username
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - db